export const COLORS = {
  bg: "#07111f",
  bg2: "#0d1830",
  panel: "rgba(17, 24, 39, 0.82)",
  panelStrong: "rgba(15, 23, 42, 0.9)",
  border: "rgba(148, 163, 184, 0.18)",
  text: "#e5ecff",
  textMuted: "#9aa9c7",
  gain: "#35d7a5",
  loss: "#ff6b7d",
  amber: "#f7b955",
  accent: "#7aa2ff",
  accent2: "#7ef0d5",
};

export const styles = {
  app: {
    display: "flex",
    minHeight: "100vh",
    background:
      "radial-gradient(circle at top left, rgba(122,162,255,0.16), transparent 35%), radial-gradient(circle at bottom right, rgba(126,240,213,0.10), transparent 30%), linear-gradient(135deg, #07111f 0%, #0d1830 55%, #111827 100%)",
    color: COLORS.text,
    transition: "all 0.25s ease",
  },
  sidebar: {
    width: 220,
    borderRight: `1px solid ${COLORS.border}`,
    padding: "20px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    flexShrink: 0,
    position: "sticky",
    top: 0,
    height: "100vh",
    background: "rgba(10, 16, 28, 0.72)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    boxShadow: "inset -1px 0 0 rgba(255,255,255,0.04)",
  },
  brand: { display: "flex", alignItems: "center", gap: 10, padding: "6px 8px 12px" },
  brandMark: {
    width: 10,
    height: 10,
    background: "linear-gradient(135deg, #7ef0d5, #7aa2ff)",
    borderRadius: 3,
    boxShadow: "0 0 16px rgba(122,162,255,0.8)",
  },
  brandText: { fontSize: 15, fontWeight: 700, letterSpacing: 0.2, color: COLORS.text },
  nav: { display: "flex", flexDirection: "column", gap: 6 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid transparent",
    background: "transparent",
    color: COLORS.textMuted,
    fontSize: 13.5,
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.18s ease",
    boxShadow: "none",
  },
  navItemActive: {
    background: "linear-gradient(135deg, rgba(122,162,255,0.22), rgba(126,240,213,0.14))",
    color: COLORS.text,
    border: `1px solid ${COLORS.border}`,
    boxShadow: "0 10px 30px rgba(122,162,255,0.12)",
  },
  navBadge: {
    marginLeft: "auto",
    fontSize: 10.5,
    background: "linear-gradient(135deg, #f7b955, #ffdd7b)",
    color: "#1a1a1a",
    borderRadius: 999,
    padding: "2px 7px",
    fontWeight: 700,
  },
  sidebarFoot: {
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 12,
    borderTop: `1px solid ${COLORS.border}`,
  },
  liveRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    color: COLORS.textMuted,
    padding: "0 6px",
  },
  userRow: { fontSize: 12, color: COLORS.textMuted, padding: "0 6px" },
  logoutBtn: {
    background: "rgba(148,163,184,0.06)",
    border: `1px solid ${COLORS.border}`,
    color: COLORS.textMuted,
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 12,
    cursor: "pointer",
    transition: "all 0.18s ease",
  },
  main: { flex: 1, padding: "30px 32px 40px", maxWidth: 1200, width: "100%" },
  header: { marginBottom: 20 },
  h1: { fontSize: 22, fontWeight: 700, margin: 0, letterSpacing: -0.3 },
  hsub: { fontSize: 13, color: COLORS.textMuted, margin: "6px 0 0" },
  indexStrip: { display: "flex", gap: 14, marginBottom: 20, flexWrap: "wrap" },
  indexCard: {
    flex: 1,
    minWidth: 180,
    background: "linear-gradient(135deg, rgba(22,30,45,0.9), rgba(12,19,32,0.88))",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 18,
    padding: "16px 18px",
    boxShadow: "0 16px 35px rgba(2,6,23,0.28)",
    transition: "transform 0.18s ease, border-color 0.18s ease",
  },
  indexLabel: { fontSize: 12, color: COLORS.textMuted, marginBottom: 6 },
  indexValue: { fontSize: 22, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  twoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  panel: {
    background: "linear-gradient(180deg, rgba(17,24,39,0.85), rgba(15,23,42,0.9))",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 18,
    padding: 18,
    boxShadow: "0 14px 28px rgba(2,6,23,0.22)",
    transition: "transform 0.18s ease, border-color 0.18s ease",
  },
  panelTitle: { fontSize: 12.5, color: COLORS.textMuted, marginBottom: 12, fontWeight: 600 },
  heatGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))",
    gap: 10,
  },
  heatCell: {
    borderRadius: 14,
    padding: "12px 10px",
    color: "#08111d",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.18)",
  },
  heatLabel: { fontSize: 12, fontWeight: 700 },
  heatValue: { fontSize: 13, marginTop: 4, fontVariantNumeric: "tabular-nums" },
  moverRow: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    background: "rgba(148,163,184,0.02)",
    border: "none",
    color: COLORS.text,
    padding: "9px 10px",
    cursor: "pointer",
    fontSize: 13.5,
    borderBottom: `1px solid ${COLORS.border}`,
    fontVariantNumeric: "tabular-nums",
    transition: "background 0.18s ease, transform 0.18s ease",
    borderRadius: 10,
  },
  stockTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: 12,
  },
  stockPrice: { fontSize: 34, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  stockChange: { display: "flex", alignItems: "center", gap: 6, fontSize: 14, marginTop: 4 },
  watchBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(122,162,255,0.08)",
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    borderRadius: 10,
    padding: "9px 12px",
    fontSize: 12.5,
    cursor: "pointer",
    transition: "all 0.18s ease",
  },
  statRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    fontSize: 13,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  statLabel: { color: COLORS.textMuted },
  statValue: { fontWeight: 600, fontVariantNumeric: "tabular-nums" },
  tableRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 10px",
    borderBottom: `1px solid ${COLORS.border}`,
    borderRadius: 10,
    transition: "background 0.18s ease",
  },
  tableRowMain: {
    flex: 1,
    display: "flex",
    gap: 10,
    alignItems: "baseline",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    color: COLORS.text,
    minWidth: 0,
  },
  tableSymbol: { fontSize: 13.5, fontWeight: 700, whiteSpace: "nowrap" },
  tableName: {
    fontSize: 12,
    color: COLORS.textMuted,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  tablePrice: { fontSize: 13.5, width: 90, textAlign: "right", fontVariantNumeric: "tabular-nums" },
  tableChange: { fontSize: 13, width: 70, textAlign: "right", fontVariantNumeric: "tabular-nums" },
  iconBtn: {
    background: "transparent",
    border: "none",
    color: COLORS.textMuted,
    cursor: "pointer",
    padding: 4,
    transition: "transform 0.18s ease",
  },
  chipRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "rgba(148,163,184,0.05)",
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    borderRadius: 999,
    padding: "7px 10px",
    fontSize: 12.5,
    cursor: "pointer",
    transition: "all 0.18s ease",
  },
  form: { display: "flex", gap: 8, flexWrap: "wrap" },
  select: {
    background: "rgba(15, 23, 42, 0.9)",
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    borderRadius: 10,
    padding: "9px 12px",
    fontSize: 13,
  },
  input: {
    background: "rgba(15, 23, 42, 0.9)",
    border: `1px solid ${COLORS.border}`,
    color: COLORS.text,
    borderRadius: 10,
    padding: "9px 12px",
    fontSize: 13,
    width: 120,
  },
  primaryBtn: {
    background: "linear-gradient(135deg, #7aa2ff, #7ef0d5)",
    border: "none",
    color: "#07111f",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 12px 26px rgba(122,162,255,0.28)",
    transition: "transform 0.18s ease, box-shadow 0.18s ease",
  },
  dangerBtn: {
    background: "rgba(255,107,125,0.08)",
    border: `1px solid ${COLORS.loss}`,
    color: COLORS.loss,
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.18s ease",
  },
  alertRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "10px 0",
    fontSize: 13,
    borderBottom: `1px solid ${COLORS.border}`,
    gap: 8,
  },
  holdingRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "11px 0",
    borderBottom: `1px solid ${COLORS.border}`,
  },
  holdingSymbol: { fontSize: 13.5, fontWeight: 700 },
  holdingMeta: { fontSize: 12, color: COLORS.textMuted },
  errorBanner: {
    background: "rgba(255,107,125,0.10)",
    border: `1px solid ${COLORS.loss}`,
    color: COLORS.loss,
    borderRadius: 12,
    padding: "10px 12px",
    fontSize: 13,
    marginBottom: 12,
  },
  toast: {
    position: "fixed",
    top: 18,
    right: 18,
    background: "rgba(15, 23, 42, 0.88)",
    border: `1px solid ${COLORS.amber}`,
    borderRadius: 14,
    padding: "12px 16px",
    fontSize: 13,
    maxWidth: 300,
    zIndex: 50,
    backdropFilter: "blur(8px)",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.28)",
  },
  authWrap: {
    minHeight: "100vh",
    background:
      "radial-gradient(circle at center, rgba(122,162,255,0.12), transparent 35%), linear-gradient(135deg, #07111f 0%, #0d1830 100%)",
    color: COLORS.text,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  authCard: {
    background: "linear-gradient(180deg, rgba(17,24,39,0.9), rgba(15,23,42,0.95))",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 18,
    padding: 28,
    width: 360,
    boxShadow: "0 26px 60px rgba(0,0,0,0.34)",
    borderTop: "1px solid rgba(122,162,255,0.25)",
  },
};

export function heatColor(pctChange) {
  const clamped = Math.max(-2, Math.min(2, pctChange));
  const t = (clamped + 2) / 4;
  const r = Math.round(228 - t * (228 - 45));
  const g = Math.round(102 + t * (212 - 102));
  const b = Math.round(123 + t * (167 - 123));
  return `rgb(${r}, ${g}, ${b})`;
}

export function pct(price, prev) {
  return ((price - prev) / prev) * 100;
}
